name: Tests

on:
    push:
        branches:
            - '**'
    workflow_dispatch:

concurrency:
    group: tests-${{ github.ref }}
    cancel-in-progress: true

env:
    DOD_TEST_ENV: github

jobs:
    run:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 3
        strategy:
            matrix:
                php-versions: [ '8.1', '8.2', '8.3' ]
            fail-fast: false
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none
                    tools: composer:v2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer install --no-progress

            -   name: Run pest tests
                run: vendor/bin/pest
